### ISSUE TITLE
Decorator and ThreadLocal doesn't work

### ISSUE THREAD

**Issue by recursiveribbons** [Adobe-Consulting-Services/acs-aem-samples#66]
In SampleResourceDecorator, it mentioned that an HttpServletRequest is no longer called, so a ThreadLocal Sling Filter may be used. However, in my own testing, the Resource Decorator is always called before the Filtering happens, therefore it always receives the default value of the ThreadLocal and not the value from the actual request.

**Comment by davidjgonzalez** [comment]
@recursiveribbons So a few things ... 
1) The resource resolution happens BEFORE the *sling* filter chain. (the OSGi Servlet filter chain happens before Sling HTTP engine is engaged).
2) You can adjust the order of Sling Filters (ie. so they are the first Sling Filter to execute).
3) In the example, the ThreadLocalOSGiService (which is what's used to retrieve the Thread Local value) gets it off the ThreadLocal object [1] so that return value will change as the ThreadLocal value is set.

So if you are getting the initial value then
1) The resource decoration is happening before your sling filter is invoked (or at least before you Set the ThreadLocal in your Filter)...
a) Which could mean that your Filter order should be earlier in the chain (ex. if you need this decoration is a later Filter)
b) You need it in the Sling Engine prior to the filter chain, which means your out of luck.
2) Your getter for the TheadLocal value is not getting it directly from the ThreadLocal object, but rather saving/reading it from filter instance variable.

How/when are you accessing the resource object where it has the incorrect (initial values)?

[1] https://github.com/Adobe-Consulting-Services/acs-aem-samples/blob/master/bundle/src/main/java/com/adobe/acs/samples/filters/impl/SampleThreadLocalFilter.java#L132

**Comment by recursiveribbons** [comment]
@davidjgonzalez

The filter is already the first in the chain, but that doesn't make a difference, as I'm not accessing the variable from another filter.

[This](https://github.com/Adobe-Consulting-Services/acs-aem-samples/blob/007ea839f08f83a6b81fae666e2564bb36a037b2/bundle/src/main/java/com/adobe/acs/samples/resources/impl/SampleResourceDecorator.java#L73) is what I'm trying to achieve. Accessing Request information from the context of a ResourceDecorator.

By writing into a log whenever a function is called, I determined that [ResourceDecorator.decorate()](https://github.com/Adobe-Consulting-Services/acs-aem-samples/blob/007ea839f08f83a6b81fae666e2564bb36a037b2/bundle/src/main/java/com/adobe/acs/samples/resources/impl/SampleResourceDecorator.java#L47) is called before [Filter.doFilter()](https://github.com/Adobe-Consulting-Services/acs-aem-samples/blob/007ea839f08f83a6b81fae666e2564bb36a037b2/bundle/src/main/java/com/adobe/acs/samples/filters/impl/SampleThreadLocalFilter.java#L102), therefore the get() function will always return the initialValue().

With your first point, are you suggesting that a normal servlet.Filter can be used instead of a Sling Filter? This should not work, as I require the information stored in a SlingHttpServletRequest.

**Comment by davidjgonzalez** [comment]
So you’re tying to decorate the resource from request.getResource() ?

Are you you trying to set a value on the value map?

**Comment by recursiveribbons** [comment]
I'm trying to set the ValueMap in the ResourceDecorator based on a certain value in SlingHttpServletRequest.

The official Sling documentation mentions ThreadLocal, and every blog post I've read points to this repo.

**Comment by recursiveribbons** [comment]
After experimenting in Sling, I believe using a [o.a.s.a.w.SlingHttpServletRequestWrapper](https://sling.apache.org/apidocs/sling7/org/apache/sling/api/wrappers/SlingHttpServletRequestWrapper.html) inside of a j.s.Filter and passing it down the FilterChain is a much better solution than using a ThreadLocal.

**Comment by davidjgonzalez** [comment]
@recursiveribbons mm - that can work; there are some assumptions being made about how that data is going to be accesed them.... for example, some code might do things like

```
doSomeWork(request.getResourceResolver(), request.getResource().getPath());

 doSomeWork(rr, path) { 
   Resource r = rr.getResource(path);
    r.getValueMap().get("setInTheFilter", "foo");
}
```

So make sure you clearly communicate this out today and in the future. The Decorator is nice in that its agnostic to this.

**Comment by recursiveribbons** [comment]
I'm not sure what you mean, because you cannot access the Sling Request from a Decorator. That's why it was suggested to use ThreadLocal. And the suggestion doesn't work.

I mean I am already able to do what I wanted to do with another method, but I still believe the suggestion given in the sources here is wrong, as I mentioned in the first two posts. If you're really sure it works, I'll close it.

**Comment by henrykuijpers** [comment]
An example of such `ThreadLocal`-approach can be found in: https://wcm.io/sling/commons/jacoco/io.wcm.sling.commons.request.impl/RequestContextFilterImpl.java.html

Of course it depends on your needs and also it depends on whether you're working with HTTP Filters or Sling Filters. The former will never work with such approach.

(By using the RequestContextFilterImpl, it's possible to then use `@Reference RequestContext requestContext` in your ResourceDecorator and you can then call `requestContext.getThreadRequest()` to obtain the request that is being processed, see also: https://wcm.io/sling/commons/apidocs/io/wcm/sling/commons/request/RequestContext.html )
